package github.zimoyin.core.barrage.com.proto;//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: test.proto
//
//package github.zimoyin.core.barrage.com.proto;
//
//public final class FirstProtobuf {
//  private FirstProtobuf() {}
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistryLite registry) {
//  }
//
//  public static void registerAllExtensions(
//      com.google.protobuf.ExtensionRegistry registry) {
//    registerAllExtensions(
//        (com.google.protobuf.ExtensionRegistryLite) registry);
//  }
//  public interface TestBufOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:TestBuf)
//      com.google.protobuf.MessageOrBuilder {
//
//    /**
//     * <code>required int32 ID = 1;</code>
//     * @return Whether the iD field is set.
//     */
//    boolean hasID();
//    /**
//     * <code>required int32 ID = 1;</code>
//     * @return The iD.
//     */
//    int getID();
//
//    /**
//     * <code>required string Url = 2;</code>
//     * @return Whether the url field is set.
//     */
//    boolean hasUrl();
//    /**
//     * <code>required string Url = 2;</code>
//     * @return The url.
//     */
//    String getUrl();
//    /**
//     * <code>required string Url = 2;</code>
//     * @return The bytes for url.
//     */
//    com.google.protobuf.ByteString
//        getUrlBytes();
//  }
//  /**
//   * Protobuf type {@code TestBuf}
//   */
//  public static final class TestBuf extends
//      com.google.protobuf.GeneratedMessageV3 implements
//      // @@protoc_insertion_point(message_implements:TestBuf)
//      TestBufOrBuilder {
//  private static final long serialVersionUID = 0L;
//    // Use TestBuf.newBuilder() to construct.
//    private TestBuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
//      super(builder);
//    }
//    private TestBuf() {
//      url_ = "";
//    }
//
//    @Override
//    @SuppressWarnings({"unused"})
//    protected Object newInstance(
//        UnusedPrivateParameter unused) {
//      return new TestBuf();
//    }
//
//    @Override
//    public final com.google.protobuf.UnknownFieldSet
//    getUnknownFields() {
//      return this.unknownFields;
//    }
//    private TestBuf(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      this();
//      if (extensionRegistry == null) {
//        throw new NullPointerException();
//      }
//      int mutable_bitField0_ = 0;
//      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
//          com.google.protobuf.UnknownFieldSet.newBuilder();
//      try {
//        boolean done = false;
//        while (!done) {
//          int tag = input.readTag();
//          switch (tag) {
//            case 0:
//              done = true;
//              break;
//            case 8: {
//              bitField0_ |= 0x00000001;
//              iD_ = input.readInt32();
//              break;
//            }
//            case 18: {
//              com.google.protobuf.ByteString bs = input.readBytes();
//              bitField0_ |= 0x00000002;
//              url_ = bs;
//              break;
//            }
//            default: {
//              if (!parseUnknownField(
//                  input, unknownFields, extensionRegistry, tag)) {
//                done = true;
//              }
//              break;
//            }
//          }
//        }
//      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//        throw e.setUnfinishedMessage(this);
//      } catch (java.io.IOException e) {
//        throw new com.google.protobuf.InvalidProtocolBufferException(
//            e).setUnfinishedMessage(this);
//      } finally {
//        this.unknownFields = unknownFields.build();
//        makeExtensionsImmutable();
//      }
//    }
//    public static final com.google.protobuf.Descriptors.Descriptor
//        getDescriptor() {
//      return com.proto.FirstProtobuf.internal_static_TestBuf_descriptor;
//    }
//
//    @Override
//    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//        internalGetFieldAccessorTable() {
//      return com.proto.FirstProtobuf.internal_static_TestBuf_fieldAccessorTable
//          .ensureFieldAccessorsInitialized(
//              com.proto.FirstProtobuf.TestBuf.class, com.proto.FirstProtobuf.TestBuf.Builder.class);
//    }
//
//    private int bitField0_;
//    public static final int ID_FIELD_NUMBER = 1;
//    private int iD_;
//    /**
//     * <code>required int32 ID = 1;</code>
//     * @return Whether the iD field is set.
//     */
//    @Override
//    public boolean hasID() {
//      return ((bitField0_ & 0x00000001) != 0);
//    }
//    /**
//     * <code>required int32 ID = 1;</code>
//     * @return The iD.
//     */
//    @Override
//    public int getID() {
//      return iD_;
//    }
//
//    public static final int URL_FIELD_NUMBER = 2;
//    private volatile Object url_;
//    /**
//     * <code>required string Url = 2;</code>
//     * @return Whether the url field is set.
//     */
//    @Override
//    public boolean hasUrl() {
//      return ((bitField0_ & 0x00000002) != 0);
//    }
//    /**
//     * <code>required string Url = 2;</code>
//     * @return The url.
//     */
//    @Override
//    public String getUrl() {
//      Object ref = url_;
//      if (ref instanceof String) {
//        return (String) ref;
//      } else {
//        com.google.protobuf.ByteString bs =
//            (com.google.protobuf.ByteString) ref;
//        String s = bs.toStringUtf8();
//        if (bs.isValidUtf8()) {
//          url_ = s;
//        }
//        return s;
//      }
//    }
//    /**
//     * <code>required string Url = 2;</code>
//     * @return The bytes for url.
//     */
//    @Override
//    public com.google.protobuf.ByteString
//        getUrlBytes() {
//      Object ref = url_;
//      if (ref instanceof String) {
//        com.google.protobuf.ByteString b =
//            com.google.protobuf.ByteString.copyFromUtf8(
//                (String) ref);
//        url_ = b;
//        return b;
//      } else {
//        return (com.google.protobuf.ByteString) ref;
//      }
//    }
//
//    private byte memoizedIsInitialized = -1;
//    @Override
//    public final boolean isInitialized() {
//      byte isInitialized = memoizedIsInitialized;
//      if (isInitialized == 1) return true;
//      if (isInitialized == 0) return false;
//
//      if (!hasID()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      if (!hasUrl()) {
//        memoizedIsInitialized = 0;
//        return false;
//      }
//      memoizedIsInitialized = 1;
//      return true;
//    }
//
//    @Override
//    public void writeTo(com.google.protobuf.CodedOutputStream output)
//                        throws java.io.IOException {
//      if (((bitField0_ & 0x00000001) != 0)) {
//        output.writeInt32(1, iD_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
//      }
//      unknownFields.writeTo(output);
//    }
//
//    @Override
//    public int getSerializedSize() {
//      int size = memoizedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (((bitField0_ & 0x00000001) != 0)) {
//        size += com.google.protobuf.CodedOutputStream
//          .computeInt32Size(1, iD_);
//      }
//      if (((bitField0_ & 0x00000002) != 0)) {
//        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
//      }
//      size += unknownFields.getSerializedSize();
//      memoizedSize = size;
//      return size;
//    }
//
//    @Override
//    public boolean equals(final Object obj) {
//      if (obj == this) {
//       return true;
//      }
//      if (!(obj instanceof com.proto.FirstProtobuf.TestBuf)) {
//        return super.equals(obj);
//      }
//      com.proto.FirstProtobuf.TestBuf other = (com.proto.FirstProtobuf.TestBuf) obj;
//
//      if (hasID() != other.hasID()) return false;
//      if (hasID()) {
//        if (getID()
//            != other.getID()) return false;
//      }
//      if (hasUrl() != other.hasUrl()) return false;
//      if (hasUrl()) {
//        if (!getUrl()
//            .equals(other.getUrl())) return false;
//      }
//      if (!unknownFields.equals(other.unknownFields)) return false;
//      return true;
//    }
//
//    @Override
//    public int hashCode() {
//      if (memoizedHashCode != 0) {
//        return memoizedHashCode;
//      }
//      int hash = 41;
//      hash = (19 * hash) + getDescriptor().hashCode();
//      if (hasID()) {
//        hash = (37 * hash) + ID_FIELD_NUMBER;
//        hash = (53 * hash) + getID();
//      }
//      if (hasUrl()) {
//        hash = (37 * hash) + URL_FIELD_NUMBER;
//        hash = (53 * hash) + getUrl().hashCode();
//      }
//      hash = (29 * hash) + unknownFields.hashCode();
//      memoizedHashCode = hash;
//      return hash;
//    }
//
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        java.nio.ByteBuffer data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        java.nio.ByteBuffer data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        com.google.protobuf.ByteString data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        com.google.protobuf.ByteString data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(byte[] data)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        byte[] data,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws com.google.protobuf.InvalidProtocolBufferException {
//      return PARSER.parseFrom(data, extensionRegistry);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseDelimitedFrom(
//        java.io.InputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        com.google.protobuf.CodedInputStream input)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input);
//    }
//    public static com.proto.FirstProtobuf.TestBuf parseFrom(
//        com.google.protobuf.CodedInputStream input,
//        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return com.google.protobuf.GeneratedMessageV3
//          .parseWithIOException(PARSER, input, extensionRegistry);
//    }
//
//    @Override
//    public Builder newBuilderForType() { return newBuilder(); }
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(com.proto.FirstProtobuf.TestBuf prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//    @Override
//    public Builder toBuilder() {
//      return this == DEFAULT_INSTANCE
//          ? new Builder() : new Builder().mergeFrom(this);
//    }
//
//    @Override
//    protected Builder newBuilderForType(
//        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//      Builder builder = new Builder(parent);
//      return builder;
//    }
//    /**
//     * Protobuf type {@code TestBuf}
//     */
//    public static final class Builder extends
//        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
//        // @@protoc_insertion_point(builder_implements:TestBuf)
//        com.proto.FirstProtobuf.TestBufOrBuilder {
//      public static final com.google.protobuf.Descriptors.Descriptor
//          getDescriptor() {
//        return com.proto.FirstProtobuf.internal_static_TestBuf_descriptor;
//      }
//
//      @Override
//      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//          internalGetFieldAccessorTable() {
//        return com.proto.FirstProtobuf.internal_static_TestBuf_fieldAccessorTable
//            .ensureFieldAccessorsInitialized(
//                com.proto.FirstProtobuf.TestBuf.class, com.proto.FirstProtobuf.TestBuf.Builder.class);
//      }
//
//      // Construct using com.proto.FirstProtobuf.TestBuf.newBuilder()
//      private Builder() {
//        maybeForceBuilderInitialization();
//      }
//
//      private Builder(
//          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
//        super(parent);
//        maybeForceBuilderInitialization();
//      }
//      private void maybeForceBuilderInitialization() {
//        if (com.google.protobuf.GeneratedMessageV3
//                .alwaysUseFieldBuilders) {
//        }
//      }
//      @Override
//      public Builder clear() {
//        super.clear();
//        iD_ = 0;
//        bitField0_ = (bitField0_ & ~0x00000001);
//        url_ = "";
//        bitField0_ = (bitField0_ & ~0x00000002);
//        return this;
//      }
//
//      @Override
//      public com.google.protobuf.Descriptors.Descriptor
//          getDescriptorForType() {
//        return com.proto.FirstProtobuf.internal_static_TestBuf_descriptor;
//      }
//
//      @Override
//      public com.proto.FirstProtobuf.TestBuf getDefaultInstanceForType() {
//        return com.proto.FirstProtobuf.TestBuf.getDefaultInstance();
//      }
//
//      @Override
//      public com.proto.FirstProtobuf.TestBuf build() {
//        com.proto.FirstProtobuf.TestBuf result = buildPartial();
//        if (!result.isInitialized()) {
//          throw newUninitializedMessageException(result);
//        }
//        return result;
//      }
//
//      @Override
//      public com.proto.FirstProtobuf.TestBuf buildPartial() {
//        com.proto.FirstProtobuf.TestBuf result = new com.proto.FirstProtobuf.TestBuf(this);
//        int from_bitField0_ = bitField0_;
//        int to_bitField0_ = 0;
//        if (((from_bitField0_ & 0x00000001) != 0)) {
//          result.iD_ = iD_;
//          to_bitField0_ |= 0x00000001;
//        }
//        if (((from_bitField0_ & 0x00000002) != 0)) {
//          to_bitField0_ |= 0x00000002;
//        }
//        result.url_ = url_;
//        result.bitField0_ = to_bitField0_;
//        onBuilt();
//        return result;
//      }
//
//      @Override
//      public Builder clone() {
//        return super.clone();
//      }
//      @Override
//      public Builder setField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return super.setField(field, value);
//      }
//      @Override
//      public Builder clearField(
//          com.google.protobuf.Descriptors.FieldDescriptor field) {
//        return super.clearField(field);
//      }
//      @Override
//      public Builder clearOneof(
//          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
//        return super.clearOneof(oneof);
//      }
//      @Override
//      public Builder setRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          int index, Object value) {
//        return super.setRepeatedField(field, index, value);
//      }
//      @Override
//      public Builder addRepeatedField(
//          com.google.protobuf.Descriptors.FieldDescriptor field,
//          Object value) {
//        return super.addRepeatedField(field, value);
//      }
//      @Override
//      public Builder mergeFrom(com.google.protobuf.Message other) {
//        if (other instanceof com.proto.FirstProtobuf.TestBuf) {
//          return mergeFrom((com.proto.FirstProtobuf.TestBuf)other);
//        } else {
//          super.mergeFrom(other);
//          return this;
//        }
//      }
//
//      public Builder mergeFrom(com.proto.FirstProtobuf.TestBuf other) {
//        if (other == com.proto.FirstProtobuf.TestBuf.getDefaultInstance()) return this;
//        if (other.hasID()) {
//          setID(other.getID());
//        }
//        if (other.hasUrl()) {
//          bitField0_ |= 0x00000002;
//          url_ = other.url_;
//          onChanged();
//        }
//        this.mergeUnknownFields(other.unknownFields);
//        onChanged();
//        return this;
//      }
//
//      @Override
//      public final boolean isInitialized() {
//        if (!hasID()) {
//          return false;
//        }
//        if (!hasUrl()) {
//          return false;
//        }
//        return true;
//      }
//
//      @Override
//      public Builder mergeFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws java.io.IOException {
//        com.proto.FirstProtobuf.TestBuf parsedMessage = null;
//        try {
//          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
//        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
//          parsedMessage = (com.proto.FirstProtobuf.TestBuf) e.getUnfinishedMessage();
//          throw e.unwrapIOException();
//        } finally {
//          if (parsedMessage != null) {
//            mergeFrom(parsedMessage);
//          }
//        }
//        return this;
//      }
//      private int bitField0_;
//
//      private int iD_ ;
//      /**
//       * <code>required int32 ID = 1;</code>
//       * @return Whether the iD field is set.
//       */
//      @Override
//      public boolean hasID() {
//        return ((bitField0_ & 0x00000001) != 0);
//      }
//      /**
//       * <code>required int32 ID = 1;</code>
//       * @return The iD.
//       */
//      @Override
//      public int getID() {
//        return iD_;
//      }
//      /**
//       * <code>required int32 ID = 1;</code>
//       * @param value The iD to set.
//       * @return This builder for chaining.
//       */
//      public Builder setID(int value) {
//        bitField0_ |= 0x00000001;
//        iD_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required int32 ID = 1;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearID() {
//        bitField0_ = (bitField0_ & ~0x00000001);
//        iD_ = 0;
//        onChanged();
//        return this;
//      }
//
//      private Object url_ = "";
//      /**
//       * <code>required string Url = 2;</code>
//       * @return Whether the url field is set.
//       */
//      public boolean hasUrl() {
//        return ((bitField0_ & 0x00000002) != 0);
//      }
//      /**
//       * <code>required string Url = 2;</code>
//       * @return The url.
//       */
//      public String getUrl() {
//        Object ref = url_;
//        if (!(ref instanceof String)) {
//          com.google.protobuf.ByteString bs =
//              (com.google.protobuf.ByteString) ref;
//          String s = bs.toStringUtf8();
//          if (bs.isValidUtf8()) {
//            url_ = s;
//          }
//          return s;
//        } else {
//          return (String) ref;
//        }
//      }
//      /**
//       * <code>required string Url = 2;</code>
//       * @return The bytes for url.
//       */
//      public com.google.protobuf.ByteString
//          getUrlBytes() {
//        Object ref = url_;
//        if (ref instanceof String) {
//          com.google.protobuf.ByteString b =
//              com.google.protobuf.ByteString.copyFromUtf8(
//                  (String) ref);
//          url_ = b;
//          return b;
//        } else {
//          return (com.google.protobuf.ByteString) ref;
//        }
//      }
//      /**
//       * <code>required string Url = 2;</code>
//       * @param value The url to set.
//       * @return This builder for chaining.
//       */
//      public Builder setUrl(
//          String value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        url_ = value;
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string Url = 2;</code>
//       * @return This builder for chaining.
//       */
//      public Builder clearUrl() {
//        bitField0_ = (bitField0_ & ~0x00000002);
//        url_ = getDefaultInstance().getUrl();
//        onChanged();
//        return this;
//      }
//      /**
//       * <code>required string Url = 2;</code>
//       * @param value The bytes for url to set.
//       * @return This builder for chaining.
//       */
//      public Builder setUrlBytes(
//          com.google.protobuf.ByteString value) {
//        if (value == null) {
//    throw new NullPointerException();
//  }
//  bitField0_ |= 0x00000002;
//        url_ = value;
//        onChanged();
//        return this;
//      }
//      @Override
//      public final Builder setUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.setUnknownFields(unknownFields);
//      }
//
//      @Override
//      public final Builder mergeUnknownFields(
//          final com.google.protobuf.UnknownFieldSet unknownFields) {
//        return super.mergeUnknownFields(unknownFields);
//      }
//
//
//      // @@protoc_insertion_point(builder_scope:TestBuf)
//    }
//
//    // @@protoc_insertion_point(class_scope:TestBuf)
//    private static final com.proto.FirstProtobuf.TestBuf DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new com.proto.FirstProtobuf.TestBuf();
//    }
//
//    public static com.proto.FirstProtobuf.TestBuf getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    @Deprecated public static final com.google.protobuf.Parser<TestBuf>
//        PARSER = new com.google.protobuf.AbstractParser<TestBuf>() {
//      @Override
//      public TestBuf parsePartialFrom(
//          com.google.protobuf.CodedInputStream input,
//          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
//          throws com.google.protobuf.InvalidProtocolBufferException {
//        return new TestBuf(input, extensionRegistry);
//      }
//    };
//
//    public static com.google.protobuf.Parser<TestBuf> parser() {
//      return PARSER;
//    }
//
//    @Override
//    public com.google.protobuf.Parser<TestBuf> getParserForType() {
//      return PARSER;
//    }
//
//    @Override
//    public com.proto.FirstProtobuf.TestBuf getDefaultInstanceForType() {
//      return DEFAULT_INSTANCE;
//    }
//
//  }
//
//  private static final com.google.protobuf.Descriptors.Descriptor
//    internal_static_TestBuf_descriptor;
//  private static final
//    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
//      internal_static_TestBuf_fieldAccessorTable;
//
//  public static com.google.protobuf.Descriptors.FileDescriptor
//      getDescriptor() {
//    return descriptor;
//  }
//  private static  com.google.protobuf.Descriptors.FileDescriptor
//      descriptor;
//  static {
//    String[] descriptorData = {
//      "\n\ntest.proto\"\"\n\007TestBuf\022\n\n\002ID\030\001 \002(\005\022\013\n\003U" +
//      "rl\030\002 \002(\tB\032\n\tcom.protoB\rFirstProtobuf"
//    };
//    descriptor = com.google.protobuf.Descriptors.FileDescriptor
//      .internalBuildGeneratedFileFrom(descriptorData,
//        new com.google.protobuf.Descriptors.FileDescriptor[] {
//        });
//    internal_static_TestBuf_descriptor =
//      getDescriptor().getMessageTypes().get(0);
//    internal_static_TestBuf_fieldAccessorTable = new
//      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
//        internal_static_TestBuf_descriptor,
//        new String[] { "ID", "Url", });
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
