// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barrage.proto

package github.zimoyin.core.barrage.com.github.proto;

public final class BarrageProto {
  private BarrageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DmSegMobileReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.DmSegMobileReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    java.util.List<DanmakuElem>
        getElemsList();
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    DanmakuElem getElems(int index);
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    int getElemsCount();
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    java.util.List<? extends DanmakuElemOrBuilder>
        getElemsOrBuilderList();
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    DanmakuElemOrBuilder getElemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.DmSegMobileReply}
   */
  public static final class DmSegMobileReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.DmSegMobileReply)
      DmSegMobileReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DmSegMobileReply.newBuilder() to construct.
    private DmSegMobileReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DmSegMobileReply() {
      elems_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DmSegMobileReply();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DmSegMobileReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                elems_ = new java.util.ArrayList<DanmakuElem>();
                mutable_bitField0_ |= 0x00000001;
              }
              elems_.add(
                  input.readMessage(DanmakuElem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          elems_ = java.util.Collections.unmodifiableList(elems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BarrageProto.internal_static_proto_DmSegMobileReply_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BarrageProto.internal_static_proto_DmSegMobileReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DmSegMobileReply.class, Builder.class);
    }

    public static final int ELEMS_FIELD_NUMBER = 1;
    private java.util.List<DanmakuElem> elems_;
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    @Override
    public java.util.List<DanmakuElem> getElemsList() {
      return elems_;
    }
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    @Override
    public java.util.List<? extends DanmakuElemOrBuilder>
        getElemsOrBuilderList() {
      return elems_;
    }
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    @Override
    public int getElemsCount() {
      return elems_.size();
    }
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    @Override
    public DanmakuElem getElems(int index) {
      return elems_.get(index);
    }
    /**
     * <code>repeated .proto.DanmakuElem elems = 1;</code>
     */
    @Override
    public DanmakuElemOrBuilder getElemsOrBuilder(
        int index) {
      return elems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < elems_.size(); i++) {
        output.writeMessage(1, elems_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < elems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, elems_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DmSegMobileReply)) {
        return super.equals(obj);
      }
      DmSegMobileReply other = (DmSegMobileReply) obj;

      if (!getElemsList()
          .equals(other.getElemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getElemsCount() > 0) {
        hash = (37 * hash) + ELEMS_FIELD_NUMBER;
        hash = (53 * hash) + getElemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DmSegMobileReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DmSegMobileReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DmSegMobileReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DmSegMobileReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DmSegMobileReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DmSegMobileReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DmSegMobileReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DmSegMobileReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DmSegMobileReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DmSegMobileReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DmSegMobileReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DmSegMobileReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DmSegMobileReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DmSegMobileReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.DmSegMobileReply)
        DmSegMobileReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BarrageProto.internal_static_proto_DmSegMobileReply_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BarrageProto.internal_static_proto_DmSegMobileReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DmSegMobileReply.class, Builder.class);
      }

      // Construct using com.github.proto.BarrageProto.DmSegMobileReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getElemsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (elemsBuilder_ == null) {
          elems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          elemsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BarrageProto.internal_static_proto_DmSegMobileReply_descriptor;
      }

      @Override
      public DmSegMobileReply getDefaultInstanceForType() {
        return DmSegMobileReply.getDefaultInstance();
      }

      @Override
      public DmSegMobileReply build() {
        DmSegMobileReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DmSegMobileReply buildPartial() {
        DmSegMobileReply result = new DmSegMobileReply(this);
        int from_bitField0_ = bitField0_;
        if (elemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            elems_ = java.util.Collections.unmodifiableList(elems_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.elems_ = elems_;
        } else {
          result.elems_ = elemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DmSegMobileReply) {
          return mergeFrom((DmSegMobileReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DmSegMobileReply other) {
        if (other == DmSegMobileReply.getDefaultInstance()) return this;
        if (elemsBuilder_ == null) {
          if (!other.elems_.isEmpty()) {
            if (elems_.isEmpty()) {
              elems_ = other.elems_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureElemsIsMutable();
              elems_.addAll(other.elems_);
            }
            onChanged();
          }
        } else {
          if (!other.elems_.isEmpty()) {
            if (elemsBuilder_.isEmpty()) {
              elemsBuilder_.dispose();
              elemsBuilder_ = null;
              elems_ = other.elems_;
              bitField0_ = (bitField0_ & ~0x00000001);
              elemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getElemsFieldBuilder() : null;
            } else {
              elemsBuilder_.addAllMessages(other.elems_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DmSegMobileReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DmSegMobileReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DanmakuElem> elems_ =
        java.util.Collections.emptyList();
      private void ensureElemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          elems_ = new java.util.ArrayList<DanmakuElem>(elems_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DanmakuElem, DanmakuElem.Builder, DanmakuElemOrBuilder> elemsBuilder_;

      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public java.util.List<DanmakuElem> getElemsList() {
        if (elemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(elems_);
        } else {
          return elemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public int getElemsCount() {
        if (elemsBuilder_ == null) {
          return elems_.size();
        } else {
          return elemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public DanmakuElem getElems(int index) {
        if (elemsBuilder_ == null) {
          return elems_.get(index);
        } else {
          return elemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder setElems(
          int index, DanmakuElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.set(index, value);
          onChanged();
        } else {
          elemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder setElems(
          int index, DanmakuElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.set(index, builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder addElems(DanmakuElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.add(value);
          onChanged();
        } else {
          elemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder addElems(
          int index, DanmakuElem value) {
        if (elemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElemsIsMutable();
          elems_.add(index, value);
          onChanged();
        } else {
          elemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder addElems(
          DanmakuElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.add(builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder addElems(
          int index, DanmakuElem.Builder builderForValue) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.add(index, builderForValue.build());
          onChanged();
        } else {
          elemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder addAllElems(
          Iterable<? extends DanmakuElem> values) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, elems_);
          onChanged();
        } else {
          elemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder clearElems() {
        if (elemsBuilder_ == null) {
          elems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          elemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public Builder removeElems(int index) {
        if (elemsBuilder_ == null) {
          ensureElemsIsMutable();
          elems_.remove(index);
          onChanged();
        } else {
          elemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public DanmakuElem.Builder getElemsBuilder(
          int index) {
        return getElemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public DanmakuElemOrBuilder getElemsOrBuilder(
          int index) {
        if (elemsBuilder_ == null) {
          return elems_.get(index);  } else {
          return elemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public java.util.List<? extends DanmakuElemOrBuilder>
           getElemsOrBuilderList() {
        if (elemsBuilder_ != null) {
          return elemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(elems_);
        }
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public DanmakuElem.Builder addElemsBuilder() {
        return getElemsFieldBuilder().addBuilder(
            DanmakuElem.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public DanmakuElem.Builder addElemsBuilder(
          int index) {
        return getElemsFieldBuilder().addBuilder(
            index, DanmakuElem.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.DanmakuElem elems = 1;</code>
       */
      public java.util.List<DanmakuElem.Builder>
           getElemsBuilderList() {
        return getElemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DanmakuElem, DanmakuElem.Builder, DanmakuElemOrBuilder>
          getElemsFieldBuilder() {
        if (elemsBuilder_ == null) {
          elemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DanmakuElem, DanmakuElem.Builder, DanmakuElemOrBuilder>(
                  elems_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          elems_ = null;
        }
        return elemsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.DmSegMobileReply)
    }

    // @@protoc_insertion_point(class_scope:proto.DmSegMobileReply)
    private static final DmSegMobileReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DmSegMobileReply();
    }

    public static DmSegMobileReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DmSegMobileReply>
        PARSER = new com.google.protobuf.AbstractParser<DmSegMobileReply>() {
      @Override
      public DmSegMobileReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DmSegMobileReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DmSegMobileReply> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DmSegMobileReply> getParserForType() {
      return PARSER;
    }

    @Override
    public DmSegMobileReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DanmakuElemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.DanmakuElem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    int getProgress();

    /**
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    int getMode();

    /**
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    int getFontsize();

    /**
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    int getColor();

    /**
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    String getMidHash();
    /**
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    com.google.protobuf.ByteString
        getMidHashBytes();

    /**
     * <code>string content = 7;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    long getCtime();

    /**
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    int getWeight();

    /**
     * <code>string action = 10;</code>
     * @return The action.
     */
    String getAction();
    /**
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    int getPool();

    /**
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    String getIdStr();
    /**
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    com.google.protobuf.ByteString
        getIdStrBytes();
  }
  /**
   * Protobuf type {@code proto.DanmakuElem}
   */
  public static final class DanmakuElem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.DanmakuElem)
      DanmakuElemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DanmakuElem.newBuilder() to construct.
    private DanmakuElem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DanmakuElem() {
      midHash_ = "";
      content_ = "";
      action_ = "";
      idStr_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DanmakuElem();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DanmakuElem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              progress_ = input.readInt32();
              break;
            }
            case 24: {

              mode_ = input.readInt32();
              break;
            }
            case 32: {

              fontsize_ = input.readInt32();
              break;
            }
            case 40: {

              color_ = input.readUInt32();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              midHash_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 64: {

              ctime_ = input.readInt64();
              break;
            }
            case 72: {

              weight_ = input.readInt32();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 88: {

              pool_ = input.readInt32();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              idStr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BarrageProto.internal_static_proto_DanmakuElem_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BarrageProto.internal_static_proto_DanmakuElem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DanmakuElem.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 2;
    private int progress_;
    /**
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    @Override
    public int getProgress() {
      return progress_;
    }

    public static final int MODE_FIELD_NUMBER = 3;
    private int mode_;
    /**
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    @Override
    public int getMode() {
      return mode_;
    }

    public static final int FONTSIZE_FIELD_NUMBER = 4;
    private int fontsize_;
    /**
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    @Override
    public int getFontsize() {
      return fontsize_;
    }

    public static final int COLOR_FIELD_NUMBER = 5;
    private int color_;
    /**
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    @Override
    public int getColor() {
      return color_;
    }

    public static final int MIDHASH_FIELD_NUMBER = 6;
    private volatile Object midHash_;
    /**
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    @Override
    public String getMidHash() {
      Object ref = midHash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        midHash_ = s;
        return s;
      }
    }
    /**
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    @Override
    public com.google.protobuf.ByteString
        getMidHashBytes() {
      Object ref = midHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        midHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private volatile Object content_;
    /**
     * <code>string content = 7;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTIME_FIELD_NUMBER = 8;
    private long ctime_;
    /**
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    @Override
    public long getCtime() {
      return ctime_;
    }

    public static final int WEIGHT_FIELD_NUMBER = 9;
    private int weight_;
    /**
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    @Override
    public int getWeight() {
      return weight_;
    }

    public static final int ACTION_FIELD_NUMBER = 10;
    private volatile Object action_;
    /**
     * <code>string action = 10;</code>
     * @return The action.
     */
    @Override
    public String getAction() {
      Object ref = action_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    @Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POOL_FIELD_NUMBER = 11;
    private int pool_;
    /**
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    @Override
    public int getPool() {
      return pool_;
    }

    public static final int IDSTR_FIELD_NUMBER = 12;
    private volatile Object idStr_;
    /**
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    @Override
    public String getIdStr() {
      Object ref = idStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idStr_ = s;
        return s;
      }
    }
    /**
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdStrBytes() {
      Object ref = idStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (progress_ != 0) {
        output.writeInt32(2, progress_);
      }
      if (mode_ != 0) {
        output.writeInt32(3, mode_);
      }
      if (fontsize_ != 0) {
        output.writeInt32(4, fontsize_);
      }
      if (color_ != 0) {
        output.writeUInt32(5, color_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(midHash_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, midHash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
      }
      if (ctime_ != 0L) {
        output.writeInt64(8, ctime_);
      }
      if (weight_ != 0) {
        output.writeInt32(9, weight_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, action_);
      }
      if (pool_ != 0) {
        output.writeInt32(11, pool_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, idStr_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (progress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, progress_);
      }
      if (mode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, mode_);
      }
      if (fontsize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, fontsize_);
      }
      if (color_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, color_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(midHash_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, midHash_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
      }
      if (ctime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, ctime_);
      }
      if (weight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, weight_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, action_);
      }
      if (pool_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, pool_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, idStr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DanmakuElem)) {
        return super.equals(obj);
      }
      DanmakuElem other = (DanmakuElem) obj;

      if (getId()
          != other.getId()) return false;
      if (getProgress()
          != other.getProgress()) return false;
      if (getMode()
          != other.getMode()) return false;
      if (getFontsize()
          != other.getFontsize()) return false;
      if (getColor()
          != other.getColor()) return false;
      if (!getMidHash()
          .equals(other.getMidHash())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getCtime()
          != other.getCtime()) return false;
      if (getWeight()
          != other.getWeight()) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (getPool()
          != other.getPool()) return false;
      if (!getIdStr()
          .equals(other.getIdStr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getProgress();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + getMode();
      hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getFontsize();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getColor();
      hash = (37 * hash) + MIDHASH_FIELD_NUMBER;
      hash = (53 * hash) + getMidHash().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCtime());
      hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getWeight();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + POOL_FIELD_NUMBER;
      hash = (53 * hash) + getPool();
      hash = (37 * hash) + IDSTR_FIELD_NUMBER;
      hash = (53 * hash) + getIdStr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DanmakuElem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DanmakuElem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DanmakuElem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DanmakuElem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DanmakuElem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DanmakuElem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DanmakuElem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DanmakuElem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DanmakuElem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DanmakuElem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DanmakuElem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DanmakuElem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DanmakuElem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DanmakuElem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.DanmakuElem)
        DanmakuElemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BarrageProto.internal_static_proto_DanmakuElem_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BarrageProto.internal_static_proto_DanmakuElem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DanmakuElem.class, Builder.class);
      }

      // Construct using com.github.proto.BarrageProto.DanmakuElem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        progress_ = 0;

        mode_ = 0;

        fontsize_ = 0;

        color_ = 0;

        midHash_ = "";

        content_ = "";

        ctime_ = 0L;

        weight_ = 0;

        action_ = "";

        pool_ = 0;

        idStr_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BarrageProto.internal_static_proto_DanmakuElem_descriptor;
      }

      @Override
      public DanmakuElem getDefaultInstanceForType() {
        return DanmakuElem.getDefaultInstance();
      }

      @Override
      public DanmakuElem build() {
        DanmakuElem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DanmakuElem buildPartial() {
        DanmakuElem result = new DanmakuElem(this);
        result.id_ = id_;
        result.progress_ = progress_;
        result.mode_ = mode_;
        result.fontsize_ = fontsize_;
        result.color_ = color_;
        result.midHash_ = midHash_;
        result.content_ = content_;
        result.ctime_ = ctime_;
        result.weight_ = weight_;
        result.action_ = action_;
        result.pool_ = pool_;
        result.idStr_ = idStr_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DanmakuElem) {
          return mergeFrom((DanmakuElem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DanmakuElem other) {
        if (other == DanmakuElem.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getProgress() != 0) {
          setProgress(other.getProgress());
        }
        if (other.getMode() != 0) {
          setMode(other.getMode());
        }
        if (other.getFontsize() != 0) {
          setFontsize(other.getFontsize());
        }
        if (other.getColor() != 0) {
          setColor(other.getColor());
        }
        if (!other.getMidHash().isEmpty()) {
          midHash_ = other.midHash_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getCtime() != 0L) {
          setCtime(other.getCtime());
        }
        if (other.getWeight() != 0) {
          setWeight(other.getWeight());
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (other.getPool() != 0) {
          setPool(other.getPool());
        }
        if (!other.getIdStr().isEmpty()) {
          idStr_ = other.idStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DanmakuElem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DanmakuElem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int progress_ ;
      /**
       * <code>int32 progress = 2;</code>
       * @return The progress.
       */
      @Override
      public int getProgress() {
        return progress_;
      }
      /**
       * <code>int32 progress = 2;</code>
       * @param value The progress to set.
       * @return This builder for chaining.
       */
      public Builder setProgress(int value) {
        
        progress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 progress = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgress() {
        
        progress_ = 0;
        onChanged();
        return this;
      }

      private int mode_ ;
      /**
       * <code>int32 mode = 3;</code>
       * @return The mode.
       */
      @Override
      public int getMode() {
        return mode_;
      }
      /**
       * <code>int32 mode = 3;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(int value) {
        
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        
        mode_ = 0;
        onChanged();
        return this;
      }

      private int fontsize_ ;
      /**
       * <code>int32 fontsize = 4;</code>
       * @return The fontsize.
       */
      @Override
      public int getFontsize() {
        return fontsize_;
      }
      /**
       * <code>int32 fontsize = 4;</code>
       * @param value The fontsize to set.
       * @return This builder for chaining.
       */
      public Builder setFontsize(int value) {
        
        fontsize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fontsize = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFontsize() {
        
        fontsize_ = 0;
        onChanged();
        return this;
      }

      private int color_ ;
      /**
       * <code>uint32 color = 5;</code>
       * @return The color.
       */
      @Override
      public int getColor() {
        return color_;
      }
      /**
       * <code>uint32 color = 5;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(int value) {
        
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 color = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = 0;
        onChanged();
        return this;
      }

      private Object midHash_ = "";
      /**
       * <code>string midHash = 6;</code>
       * @return The midHash.
       */
      public String getMidHash() {
        Object ref = midHash_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          midHash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string midHash = 6;</code>
       * @return The bytes for midHash.
       */
      public com.google.protobuf.ByteString
          getMidHashBytes() {
        Object ref = midHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          midHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string midHash = 6;</code>
       * @param value The midHash to set.
       * @return This builder for chaining.
       */
      public Builder setMidHash(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        midHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string midHash = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMidHash() {
        
        midHash_ = getDefaultInstance().getMidHash();
        onChanged();
        return this;
      }
      /**
       * <code>string midHash = 6;</code>
       * @param value The bytes for midHash to set.
       * @return This builder for chaining.
       */
      public Builder setMidHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        midHash_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 7;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 7;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 7;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long ctime_ ;
      /**
       * <code>int64 ctime = 8;</code>
       * @return The ctime.
       */
      @Override
      public long getCtime() {
        return ctime_;
      }
      /**
       * <code>int64 ctime = 8;</code>
       * @param value The ctime to set.
       * @return This builder for chaining.
       */
      public Builder setCtime(long value) {
        
        ctime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ctime = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtime() {
        
        ctime_ = 0L;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>int32 weight = 9;</code>
       * @return The weight.
       */
      @Override
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>int32 weight = 9;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(int value) {
        
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 weight = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        
        weight_ = 0;
        onChanged();
        return this;
      }

      private Object action_ = "";
      /**
       * <code>string action = 10;</code>
       * @return The action.
       */
      public String getAction() {
        Object ref = action_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string action = 10;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 10;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 10;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private int pool_ ;
      /**
       * <code>int32 pool = 11;</code>
       * @return The pool.
       */
      @Override
      public int getPool() {
        return pool_;
      }
      /**
       * <code>int32 pool = 11;</code>
       * @param value The pool to set.
       * @return This builder for chaining.
       */
      public Builder setPool(int value) {
        
        pool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pool = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearPool() {
        
        pool_ = 0;
        onChanged();
        return this;
      }

      private Object idStr_ = "";
      /**
       * <code>string idStr = 12;</code>
       * @return The idStr.
       */
      public String getIdStr() {
        Object ref = idStr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          idStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string idStr = 12;</code>
       * @return The bytes for idStr.
       */
      public com.google.protobuf.ByteString
          getIdStrBytes() {
        Object ref = idStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idStr = 12;</code>
       * @param value The idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string idStr = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdStr() {
        
        idStr_ = getDefaultInstance().getIdStr();
        onChanged();
        return this;
      }
      /**
       * <code>string idStr = 12;</code>
       * @param value The bytes for idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idStr_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.DanmakuElem)
    }

    // @@protoc_insertion_point(class_scope:proto.DanmakuElem)
    private static final DanmakuElem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DanmakuElem();
    }

    public static DanmakuElem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DanmakuElem>
        PARSER = new com.google.protobuf.AbstractParser<DanmakuElem>() {
      @Override
      public DanmakuElem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DanmakuElem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DanmakuElem> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DanmakuElem> getParserForType() {
      return PARSER;
    }

    @Override
    public DanmakuElem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DmSegMobileReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DmSegMobileReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DanmakuElem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DanmakuElem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rbarrage.proto\022\005proto\"5\n\020DmSegMobileRep" +
      "ly\022!\n\005elems\030\001 \003(\0132\022.proto.DanmakuElem\"\310\001" +
      "\n\013DanmakuElem\022\n\n\002id\030\001 \001(\003\022\020\n\010progress\030\002 " +
      "\001(\005\022\014\n\004mode\030\003 \001(\005\022\020\n\010fontsize\030\004 \001(\005\022\r\n\005c" +
      "olor\030\005 \001(\r\022\017\n\007midHash\030\006 \001(\t\022\017\n\007content\030\007" +
      " \001(\t\022\r\n\005ctime\030\010 \001(\003\022\016\n\006weight\030\t \001(\005\022\016\n\006a" +
      "ction\030\n \001(\t\022\014\n\004pool\030\013 \001(\005\022\r\n\005idStr\030\014 \001(\t" +
      "B \n\020com.github.protoB\014BarrageProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_DmSegMobileReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_DmSegMobileReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DmSegMobileReply_descriptor,
        new String[] { "Elems", });
    internal_static_proto_DanmakuElem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_DanmakuElem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DanmakuElem_descriptor,
        new String[] { "Id", "Progress", "Mode", "Fontsize", "Color", "MidHash", "Content", "Ctime", "Weight", "Action", "Pool", "IdStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
